### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by Arhs99** [wenhao-gao/synformer#1]
Thank you for publishing the code for synformer. I cannot currently test the software as one crucial file seems to be missing. That would be the file `data/processed.zip` that should be available in https://huggingface.co/whgao/synformer by the link you provide in the README. But it cannot be found there.

**Comment by wenhao-gao** [comment]
Hi, the processed.zip is not necessary. We have updated the README; please check the new instructions. Thank you!
